<?php
return [
	'player' => [
		'id' => 1,
		'contenttype' => 'video',
		'showplaylist' => 'false',
		'width' => '100%',
		'height' => 'auto',
		'controls' => 'none',
		'preload' => 'auto',
		'playlistposition' => 'bottom',
		'autoplay' => 'false',
		'autoplaysound' => 'false',
		'orderbutton' => 'false',
		'orderbuttonposition' => 'center',
		'orderbuttonlink' => '',
		'orderbuttontitle' => __('OrderButtonTitle', 'aoplayer'),
		'orderbuttoncolor' => 'default',
		'orderbuttontime' => '50',
		'orderbuttonfontsize' => '18',
		'orderbuttonleft' => '4',
		'orderbuttonright' => '4',
		'poster' => '',
		'positionplayer' => 'center',
		'controls_navigation' => 'true',
	],
	'source' => [
		0 => [
			'link' => '',
			'poster' => '',
			'title' => '',
			'type' => 'video/mp4',
		],
	],
	'rule' => [
		'id' => 'int',
		'contenttype' => 'str',
		'showplaylist' => 'boolean',
		'width' => 'intstr',
		'height' => 'intstr',
		'controls' => 'str',
		'preload' => 'str',
		'playlistposition' => 'str',
		'autoplay' => 'boolean',
		'autoplaysound' => 'boolean',
		'orderbutton' => 'boolean',
		'orderbuttonposition' => 'str',
		'orderbuttonlink' => 'url',
		'orderbuttontitle' => 'text',
		'orderbuttoncolor' => 'str',
		'orderbuttontime' => 'int',
		'orderbuttonfontsize' => 'int',
		'orderbuttonleft' => 'int',
		'orderbuttonright' => 'int',
		'positionplayer' => 'str',
		'link' => 'url',
		'poster' => 'url',
		'title' => 'text',
		'type' => 'intstr',
		'name' => 'text',
		'controls_navigation' =>  'boolean',
		'new' =>  'boolean',
	],
	'style' => [
		'default' => 'cccccc',
		'info' => '1b6d85',
		'primary' => '122b40',
		'warning' => '985f0d',
		'danger' => '761c19',
		'success' => '4cae4c',
	],
];